config/routes.rb
Rails.application.routes.draw do
  root 'vehicles#index'
  resources :vehicles, only: [ :index, :show, :new, :create, :destroy ]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/vehicle.rb
# == Schema Information
#
# Table name: vehicles
#
#  id            :integer          not null, primary key
#  vehicle_type  :string           not null
#  license_plate :string           not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  visit_count   :integer          default("0")
#  tailgate_down :boolean          default("f")
#  muddy_bed     :boolean          default("f")
#

class Vehicle < ApplicationRecord
  validates :vehicle_type, :license_plate, presence: true
  validates :license_plate, length: { is: 7 }
  validates :vehicle_type, inclusion: %w(car truck)
  validate :truck
  validates_exclusion_of :license_plate, :in => ["1111111"]

  def cost
    return 'No service' if self.tailgate_down
    "$#{ visit_cost + bed_amount }"
  end

  def visit
    self.visit_count += 1
    self.save
  end

  def truck?
    self.vehicle_type == 'truck'
  end

  private
  def truck
    if !truck?
      errors.add(:muddy_bed, "isn't part of a car") if self.muddy_bed
      errors.add(:tailgate_down, "is not possible") if self.tailgate_down
    end
  end

  def visit_cost
    amount = (truck? ? 10 : 5)
    self.visit_count > 0 ? amount / 2 : amount
  end

  def bed_amount
    self.muddy_bed ? 2 : 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.all
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    if params[:vehicle][:license_plate] == '1111111'
      respond_to do |format|
        format.html { render :template => 'vehicles/jail' }
        format.json { render json: { message: 'This vehicle has been reported stolen! We will not give service to a stolen vehicle' } }
      end
      return
    end

    @vehicle = Vehicle.find_or_create_by(license_plate: params[:vehicle][:license_plate])
    @vehicle.visit unless @vehicle.id.nil?

    respond_to do |format|
      if @vehicle.update(vehicle_params)
        if @vehicle.tailgate_down
          format.html { render :template => 'vehicles/no_service' }
          format.json { render json: { message: 'This vehicle has the tailgate down' } }
        else
          format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
          format.json { render :show, status: :created, location: @vehicle }
        end
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    def vehicle_params
      params.require(:vehicle).permit(:vehicle_type, :license_plate, :muddy_bed, :tailgate_down)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarWash</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/vehicles/_form.html.erb
<%= form_with(model: vehicle, local: true) do |form| %>
  <% if vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% vehicle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :vehicle_type %>
    <%= form.select(:vehicle_type, options_for_select(['car', 'truck'])) %>
  </div>

  <div class="field">
    <%= form.label :license_plate %>
    <%= form.text_field :license_plate, id: :vehicle_license_plate %>
  </div>

  <div class="field">
    <%= form.label :muddy_bed %>
    <%= form.check_box :muddy_bed, id: :vehicle_muddy_bed %>
  </div>

  <div class="field">
    <%= form.label :tailgate_down %>
    <%= form.check_box :tailgate_down, id: :vehicle_tailgate_down %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vehicles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vehicles</h1>

<%= link_to 'New Vehicle', new_vehicle_path %>

<table>
  <thead>
    <tr>
      <th>License plate</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.license_plate %></td>
        <td><%= vehicle.vehicle_type %></td>
        <td><%= link_to 'Show last visit', vehicle %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/vehicles/jail.html.erb
<h1>Stolen!</h1>

<p>This vehicle has been reported stolen! We will not give service to a stolen vehicle</p>

<%= link_to 'All vehicles', vehicles_path %>

app/views/vehicles/new.html.erb
<h1>New Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/no_service.html.erb
<h1>No Service</h1>

<p>Truck beds must have a tailgate</p>

<%= link_to 'All vehicles', vehicles_path %>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @vehicle.vehicle_type %>
</p>

<p>
  <strong>License plate:</strong>
  <%= @vehicle.license_plate %>
</p>

<p>
  <strong>Visit count:</strong>
  <%= @vehicle.visit_count %>
</p>

<% if @vehicle.truck? %>
  <p>
    <strong>Mud in bed:</strong>
    <%= @vehicle.muddy_bed %>
  </p>

  <p>
    <strong>Tailgate Down:</strong>
    <%= @vehicle.tailgate_down %>
  </p>
<% end %>

<p>
  <strong>Total for visit:</strong>
  <%= @vehicle.cost %>
</p>

<%= link_to 'All vehicles', vehicles_path %> |
<%= link_to 'Delete car', @vehicle, method: :delete, data: { confirm: 'Are you sure?' } %>